{{- if .Values.ingress.enabled -}}
{{- $fullName := include "adguard-home.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $servicePort := .Values.service.web.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
spec:
  entryPoints:
      - web
      - websecure
  routes:
  {{- range .Values.ingress.hosts }}
    - match: HostRegexp(`{{ .host }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $servicePort }}
  {{- end }}
  tls:
    certResolver: default
{{- end }}
