{{- if .Values.ingress.enabled -}}
{{- $fullName := include "adguard-home.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $servicePort := .Values.service.web.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "adguard-home.name" . }}
    helm.sh/chart: {{ include "adguard-home.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  entryPoints:
      - web
      - websecure
    routes:
    {{- range .Values.ingress.hosts }}
      - match: HostRegexp(`{{ .host }}`) && PathPrefix(`{{ .path }}`)
        kind: Rule
        services:
          - name: {{ $fullName }}
            port: {{ $servicePort }}
    {{- end }}
    tls:
      certResolver: default
  {{- end }}
{{- end }}
