{{- if .Values.ingress.enabled -}}
{{- $fullName := include "podinfo.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $httpPort := .Values.service.externalPort -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  {{- range .Values.ingress.hosts }}
    - match: HostRegexp(`{{ . }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $httpPort }}
  {{- end }}
  tls:
    certResolver: default
{{- end }}
