apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  namespace: transmission
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/test"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  namespace: transmission
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/storage/config/transmission
  persistentVolumeReclaimPolicy: Retain
