apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
{{- if .Values.service.web.externalIPs }}
  externalIPs:
    {{ toYaml .Values.service.web.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - name: web
      targetPort: web
      port: {{ .Values.service.web.port }}
      protocol: TCP
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-peer
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.peer.type }}
{{- if .Values.service.peer.externalIPs }}
  externalIPs:
    {{ toYaml .Values.service.peer.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - name: peer-tcp
      targetPort: peer-tcp
      port: {{ .Values.service.peer.ports.tcp }}
      protocol: TCP
    - name: peer-udp
      targetPort: peer-udp
      port: {{ .Values.service.peer.ports.udp }}
      protocol: UDP
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
