---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: organizr
  namespace: organizr
spec:
  entryPoints:
      - web
      - websecure
  routes:
    - match: HostRegexp(`organizr.{ip:.*}.nip.io`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: organizr
          port: 80
  tls:
    certResolver: default
