---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.105
spec:
  releaseName: adguard-home
  chart:
    git: https://github.com/k8s-at-home/charts
    path: charts/stable/adguard-home
    ref: adguard-home-3.0.0
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.105.2
    service:
      additionalServices:
        - enabled: true
          nameSuffix: udp
          type: NodePort
          port:
            port: 53
            name: dns-udp
            protocol: UDP
            targetPort: 53
          externalTrafficPolicy: Local
