---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~2.3
spec:
  chart:
    git: https://github.com/traefik/traefik-helm-chart.git
    path: traefik/
    ref: v9.13.0
  values:
    image:
      repository: traefik
      tag: v2.3.7
    fullnameOverride: traefik
    ports:
      dns-udp:
        port: 5353
        expose: true
        exposedPort: 53
        protocol: UDP
