---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: transmission
  namespace: transmission
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~3.00
spec:
  chart:
    git: git@github.com:abelino/k8s-homelab-flux
    path: charts/transmission
    ref: master
  values:
    image:
      repository: linuxserver/transmission
      tag: 3.00-r0-ls66
    settings:
      rpc:
        authenticationRequired: true
      download:
        dir: /downloads
      incomplete:
        enabled: false
      watch:
        enabled: false
      umask: 18
    controller:
      publishService:
        enabled: true
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    process:
      uid: "1000"
      gid: "1000"
    ingress:
      enabled: true
      hosts:
        - host: transmission.{ip:.*}.nip.io
          path: /
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: local-storage
        labels:
          type: local
      downloads:
        enabled: true
        accessMode: ReadWriteOnce
        size: 100Ti
        storageClass: local-storage
        labels:
          type: local
