---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: lab
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~5.0
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:abelino/k8s-homelab-flux
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 5.0.2
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.frontend.rule.type: PathPrefix
      hosts:
        - podinfo.alpha.local
      path: /
    replicaCount: 3
